# Generated by Django 4.1 on 2023-03-01 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_commerce', '0003_car_carbrand_color_country_customer_salesperson_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='car_commerce.region'),
        ),
    ]
