# Generated by Django 4.1 on 2023-03-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_commerce', '0004_alter_country_region_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='car_commerce.country'),
        ),
    ]
