# Generated by Django 4.1 on 2023-03-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_commerce', '0005_alter_salesperson_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_country', to='car_commerce.country'),
        ),
    ]
