# Generated by Django 4.1 on 2023-03-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_commerce', '0006_alter_carbrand_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_model', to='car_commerce.carmodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color', to='car_commerce.color'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_car', to='car_commerce.country'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='car_commerce.carbrand'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_customer', to='car_commerce.country'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='car_ir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car', to='car_commerce.car'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_making_the_sale', to='car_commerce.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_person_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_person', to='car_commerce.salesperson'),
        ),
    ]
