# Generated by Django 4.1 on 2023-03-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_commerce', '0007_alter_car_car_model_id_alter_car_color_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='car_ir',
            new_name='car_id',
        ),
    ]
