# Generated by Django 4.1 on 2023-03-06 00:10

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('car_commerce', '0009_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
