insert into car_commerce_color (name) values ('Rojo');
insert into car_commerce_color (name) values ('Verde');
insert into car_commerce_color (name) values ('Azul');
insert into car_commerce_color (name) values ('Gris');
insert into car_commerce_color (name) values ('Negro');
insert into car_commerce_color (name) values ('Dorado');
insert into car_commerce_color (name) values ('Amarillo');
insert into car_commerce_color (name) values ('Lima');
insert into car_commerce_color (name) values ('Rosa');
insert into car_commerce_color (name) values ('Celeste');
insert into car_commerce_color (name) values ('Crema');
insert into car_commerce_color (name) values ('Blanco');
insert into car_commerce_color (name) values ('Naranja');
insert into car_commerce_color (name) values ('Violeta');
insert into car_commerce_color (name) values ('Marron');
insert into car_commerce_color (name) values ('Purpura');
insert into car_commerce_color (name) values ('Verde oscuro');