name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  test-and-lint:
    name: Testing and Linting
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.2-alpine
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

  build-and-deploy:
    name: Building and Deploying
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Build new release
        run: docker build --cache-from prueba/api:latest --tag api:0.0.1-alpha .

      - name: Push new release
        run: |
          docker push prueba/api:0.0.1-alpha
          docker push prueba/api:latest
